Repository larseggert/draft-ietf-modpod-group-processes, pull requests merged in 2025-08, with the labels that each got.

#162 Remove "decide to"
  draft-ietf-modpod-group-processes.md
Labels: editorial

#157 Remove angle brackets
  draft-ietf-modpod-group-processes.md
Labels: editorial

#155 "a credible threat"
  draft-ietf-modpod-group-processes.md
Labels: needs-discussion, editorial

#176 "develop"
  draft-ietf-modpod-group-processes.md
Labels: editorial

#180 moderator team initially consists of at least
  draft-ietf-modpod-group-processes.md
Labels: editorial

#149 Suggestions by Pete
  draft-ietf-modpod-group-processes.md
Labels: needs-discussion

#200 uniform->consistent
  draft-ietf-modpod-group-processes.md
Labels: editorial
