Repository larseggert/draft-ietf-modpod-group-processes, pull requests merged in 2025-06, with the labels that each got.

#126 New attempt to address moderation/WG interactions
  draft-ietf-modpod-group-processes.md
Labels: needs-discussion

#127 Consolidate "this document/this memo".
  draft-ietf-modpod-group-processes.md
Labels: editorial

#110 Reinstatement is equivalent to an appeal
  draft-ietf-modpod-group-processes.md
Labels: finalize-pr
