Repository larseggert/draft-ietf-modpod-group-processes, pull requests merged in 2025-02, with the labels that each got.

#92 Update "Relation to the IETF LLC"
  draft-ietf-modpod-group-processes.md
Labels: completed

#103 Rewrite philosophy (again).
  draft-ietf-modpod-group-processes.md
Labels: finalize-pr

#107 Reinstatement
  draft-ietf-modpod-group-processes.md
Labels: needs-discussion

#108 clarify ban text
  draft-ietf-modpod-group-processes.md
Labels: editorial
