Repository larseggert/draft-ietf-modpod-group-processes, pull requests merged in 2025-05, with the labels that each got.

#105 feat: Say which other RFCs we obsolete and update
  draft-ietf-modpod-group-processes.md
Labels: finalize-pr

#111 Circumvention demonstrates bad faith
  draft-ietf-modpod-group-processes.md
Labels: finalize-pr, editorial

#120 Use lowercase rather than 2119 langauge
  draft-ietf-modpod-group-processes.md
Labels: needs-discussion
