Repository larseggert/draft-ietf-modpod-group-processes, pull requests merged in 2025-01, with the labels that each got.

#76 Scope and relationship between WG chairs and moderators
  draft-ietf-modpod-group-processes.md
Labels: finalize-pr

#74 On transparency.
  draft-ietf-modpod-group-processes.md
Labels: finalize-pr

#88 chore: rewording + spelling
  draft-ietf-modpod-group-processes.md
Labels: needs-review

#87 Just reword a few things.
  draft-ietf-modpod-group-processes.md
Labels: finalize-pr

#91 transparency: regression
  draft-ietf-modpod-group-processes.md
Labels: finalize-pr

#90 Fix GitHub link
  draft-ietf-modpod-group-processes.md
Labels: finalize-pr

#99 trim intro, move motivational text to Appendix
  draft-ietf-modpod-group-processes.md
Labels: needs-review, editorial

#98 Various grammar fixes
  draft-ietf-modpod-group-processes.md
Labels: needs-review, editorial

#97 Point to `draft-perkins-irtf-code-of-conduct`
  draft-ietf-modpod-group-processes.md
Labels: needs-review, editorial

#101 Add sentence to abstract.
  draft-ietf-modpod-group-processes.md
Labels: completed
